spring.application.name=owlEditor

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ontology

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=300MB
spring.servlet.multipart.file-size-threshold=10MB

java.io.tmpdir=${user.home}/temp/ontology-uploads

server.port=8083

spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100
spring.task.execution.thread-name-prefix=owl-async-

logging.level.root=INFO
logging.level.self.research.ontology=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.web.cors=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n