parent=keycloak
import=common/keycloak

# Localization
locales=en,es,fr,de,ja,zh-CN

# Email templates
styles=css/email.css

# From address
fromDisplayName=OntoCode Platform
fromEmail=noreply@ontocode.io
