spring.application.name=auth
server.port=8086

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ontology
spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=300MB

# JWT Configuration (Same as before)
jwt.secret=deeea417e35bc10f211c02c5e68aacd3c2ab230fd81a978958bb211b2b2dd554
jwt.expiration=8640000

mailtrap.api.token=fe6e525ef5abb8c622ffb15360bbd820

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG